// ============================================================
// RankMaster Pro - Site Config API
// robots.txt editor + XML sitemap generator
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { getAuthUser } from '@/lib/auth-guard';
import { z } from 'zod';

const Schema = z.object({
    action: z.enum(['get_robots', 'save_robots', 'generate_sitemap', 'push_robots', 'push_sitemap', 'get_sitemap_config', 'save_sitemap_config']),
    site_id: z.string().uuid(),
    robots_txt: z.string().max(50000).optional(),
    sitemap_config: z.object({
        include_posts: z.boolean().default(true).optional(),
        include_pages: z.boolean().default(true).optional(),
        include_categories: z.boolean().default(false).optional(),
        include_tags: z.boolean().default(false).optional(),
        change_freq: z.enum(['always','hourly','daily','weekly','monthly','yearly','never']).default('weekly').optional(),
        priority_posts: z.number().min(0).max(1).default(0.8).optional(),
        priority_pages: z.number().min(0).max(1).default(0.6).optional(),
        exclude_noindex: z.boolean().default(true).optional(),
    }).optional(),
});

function generateDefaultRobots(siteUrl: string): string {
    return `# robots.txt for ${siteUrl}
# Generated by RankMaster Pro

User-agent: *
Allow: /

# Block admin areas
Disallow: /wp-admin/
Disallow: /wp-includes/
Disallow: /wp-json/
Disallow: /?s=
Disallow: /search/

# Allow crawling of critical pages
Allow: /wp-admin/admin-ajax.php

# Sitemaps
Sitemap: ${siteUrl}/sitemap.xml
Sitemap: ${siteUrl}/post-sitemap.xml
Sitemap: ${siteUrl}/page-sitemap.xml

# Crawl-delay for heavy bots
User-agent: AhrefsBot
Crawl-delay: 10

User-agent: SemrushBot
Crawl-delay: 10

User-agent: DotBot
Disallow: /
`;
}

function generateSitemapXml(posts: Array<{ slug: string; updated_at: string; overall_score: number }>, siteUrl: string, config: Record<string, unknown>): string {
    const baseUrl = siteUrl.replace(/\/$/, '');
    const now = new Date().toISOString().split('T')[0];

    const urlEntries = posts.map(post => {
        const priority = post.overall_score >= 80 ? '0.9' : post.overall_score >= 60 ? '0.7' : '0.5';
        return `  <url>
    <loc>${baseUrl}/${post.slug}/</loc>
    <lastmod>${post.updated_at?.split('T')[0] || now}</lastmod>
    <changefreq>${config.change_freq || 'weekly'}</changefreq>
    <priority>${priority}</priority>
  </url>`;
    }).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

  <!-- Generated by RankMaster Pro on ${now} -->
  <!-- ${posts.length} URLs -->

  <url>
    <loc>${baseUrl}/</loc>
    <lastmod>${now}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>

${urlEntries}
</urlset>`;
}

export async function POST(request: NextRequest) {
    const auth = await getAuthUser();
    if (auth.error) return auth.error;

    const body = await request.json();
    const parsed = Schema.safeParse(body);
    if (!parsed.success) return NextResponse.json({ error: 'Validation failed', details: parsed.error.flatten().fieldErrors }, { status: 400 });

    const { action, site_id } = parsed.data;

    const { data: site } = await auth.supabase.from('sites').select('url, username, app_password_encrypted').eq('id', site_id).eq('user_id', auth.user.id).single();
    if (!site) return NextResponse.json({ error: 'Site not found' }, { status: 404 });

    if (action === 'get_robots') {
        const { data: config } = await auth.supabase.from('site_configs').select('robots_txt').eq('site_id', site_id).eq('user_id', auth.user.id).single();
        const robotsTxt = config?.robots_txt || generateDefaultRobots(site.url);
        return NextResponse.json({ robots_txt: robotsTxt });
    }

    if (action === 'save_robots') {
        const { robots_txt } = parsed.data;
        if (!robots_txt) return NextResponse.json({ error: 'robots_txt required' }, { status: 400 });

        await auth.supabase.from('site_configs').upsert({
            user_id: auth.user.id, site_id, robots_txt, updated_at: new Date().toISOString(),
        }, { onConflict: 'site_id' });

        return NextResponse.json({ success: true });
    }

    if (action === 'generate_sitemap') {
        const config = parsed.data.sitemap_config || {};
        const { data: posts } = await auth.supabase.from('posts').select('slug, updated_at, overall_score').eq('site_id', site_id).eq('user_id', auth.user.id).eq('status', 'published').order('overall_score', { ascending: false });

        const sitemap = generateSitemapXml(posts || [], site.url, config as Record<string, unknown>);

        await auth.supabase.from('site_configs').upsert({
            user_id: auth.user.id, site_id, sitemap_xml: sitemap, sitemap_config: config, sitemap_generated_at: new Date().toISOString(), updated_at: new Date().toISOString(),
        }, { onConflict: 'site_id' });

        return NextResponse.json({ sitemap, url_count: (posts || []).length + 1 });
    }

    if (action === 'push_robots') {
        const { data: config } = await auth.supabase.from('site_configs').select('robots_txt').eq('site_id', site_id).eq('user_id', auth.user.id).single();
        if (!config?.robots_txt) return NextResponse.json({ error: 'Save robots.txt first' }, { status: 400 });

        // Push to WordPress via REST API
        const credentials = Buffer.from(`${site.username}:${site.app_password_encrypted}`).toString('base64');
        const wpUrl = site.url.replace(/\/$/, '');

        try {
            const res = await fetch(`${wpUrl}/wp-json/rankmaster/v1/robots`, {
                method: 'POST',
                headers: { Authorization: `Basic ${credentials}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({ content: config.robots_txt }),
                signal: AbortSignal.timeout(15000),
            });

            if (res.ok) return NextResponse.json({ success: true, message: 'robots.txt pushed to WordPress' });
            return NextResponse.json({ message: 'WordPress endpoint not found. Copy robots.txt content manually to your server.', robots_txt: config.robots_txt });
        } catch {
            return NextResponse.json({ message: 'Could not reach WordPress. Copy robots.txt manually.', robots_txt: config.robots_txt });
        }
    }

    if (action === 'push_sitemap') {
        const { data: config } = await auth.supabase.from('site_configs').select('sitemap_xml').eq('site_id', site_id).eq('user_id', auth.user.id).single();
        if (!config?.sitemap_xml) return NextResponse.json({ error: 'Generate sitemap first' }, { status: 400 });

        // Submit to Google Search Console
        const gscSubmitUrl = `https://www.google.com/ping?sitemap=${encodeURIComponent(site.url.replace(/\/$/, '') + '/sitemap.xml')}`;

        return NextResponse.json({
            message: 'Sitemap generated. Submit to Google Search Console:',
            google_submit_url: gscSubmitUrl,
            sitemap_url: `${site.url.replace(/\/$/, '')}/sitemap.xml`,
            instruction: 'Upload sitemap_xml content to your server at /sitemap.xml, then submit the URL to Google Search Console.',
        });
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
}

export async function GET(request: NextRequest) {
    const auth = await getAuthUser();
    if (auth.error) return auth.error;

    const siteId = new URL(request.url).searchParams.get('site_id');
    if (!siteId) {
        const { data: sites } = await auth.supabase.from('sites').select('id, name, url').eq('user_id', auth.user.id);
        return NextResponse.json({ sites: sites || [] });
    }

    const { data } = await auth.supabase.from('site_configs').select('*').eq('site_id', siteId).eq('user_id', auth.user.id).single();
    return NextResponse.json({ config: data || {} });
}
